### ISSUE TITLE
FR: save input and expression as a share link

### ISSUE THREAD

**Issue by nathanperkins** [undistro/cel-playground#13]
## Feature Description

I would like to be able to save my expression and input and share it as link, similar to the [Go Playground](https://go.dev/play/)

## Is your feature request related to a problem?

No.

## What alternatives have you considered?

None.

## Additional Context

I totally understand that this requires making the app stateful and increases the operational costs. Feel free to reject if it's not reasonable or impose additional constraints like an expiration.

## Random Praise

Thanks for making this! It is extremely helpful for experimenting with CEL for Kubernetes CRD field validations :)

**Comment by monuelo** [comment]
Hey, @nathanperkins! Thank you for the suggestion, and glad to hear that CEL Playground has been helpful! We're looking into ways to implement this feature while keeping the app static.

A possibility is to generate a base64 encoded string from a gzip compressed JSON, which would contain the expression and input data. This string can then be added to the URL, allowing for easy sharing and retrieval of the saved state.

We appreciate your input, and we'll explore this approach further. If you have any more ideas or feedback, please let us know!  🚀

**Comment by nathanperkins** [comment]
Very clever idea, I like it :)

**Comment by nathanperkins** [comment]
So awesome! Thank you :)
