### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by matheusfm** [undistro/cel-playground#25]
## Feature Description
I'd like to request the addition of a dark mode to the CEL Playground for a better user experience.

## Is your feature request related to a problem?
No.

## What alternatives have you considered?
Implement a toggle switch on the navbar for users to switch between light and dark mode.

## Additional Context
If you'd like to work on this or have questions, please comment below for more information.

**Comment by pateldivyesh1323** [comment]
@matheusfm I would like to work on this.

**Comment by matheusfm** [comment]
Hi @pateldivyesh1323 
Your contributions are welcome. Feel free to open a PR.
Let me know if you have any questions about the feature description.

**Comment by pateldivyesh1323** [comment]
@matheusfm Do you have anything in mind about how it should be implemented or the color theme?

**Comment by matheusfm** [comment]
I just suggest adding a toggle switch to the right side of the navbar.
The color theme should be consistent with the current palette, if it makes sense. 
Please feel free to suggest colors here.

**Comment by matheusfm** [comment]
@pateldivyesh1323 can I assign this issue to you?

**Comment by matheusfm** [comment]
Yes, I think it's a good idea.

If you need an icon, please refer to [Phosphor icons](https://phosphoricons.com/).

Here are some dark-themed playgrounds for inspiration:
- https://helm-playground.com/
- https://play.permify.co/
- https://play.sqlc.dev/

**Comment by pateldivyesh1323** [comment]
@matheusfm where can I find light mode logo of cel playground?

**Comment by pateldivyesh1323** [comment]
@matheusfm I have attached the PR. Please review it.

**Comment by matheusfm** [comment]
Thank you @pateldivyesh1323. I'll review it.
