### ISSUE TITLE
Add reference links for cel-go and Language definition overview.

### ISSUE THREAD

**Issue by lucasjct** [undistro/cel-playground#27]
## Where?

I'd like to suggest to include two references links:  
    * https://github.com/google/cel-go --> at cel-go version on the footer.
    * https://github.com/google/cel-spec/blob/master/doc/langdef.md  --> create a text "Language definition" on the footer too, next to cel-go.

## Who?
It helps CEL users find  information by consulting the "Language Definition" link, which serves as an reference for learning about CEL.

**Comment by marcelloale** [comment]
Olá @lucasjct como poderia ajudar?

**Comment by lucasjct** [comment]
Hello @marcelloale ! Thank you for your interest! 

As I saw the issue above, it is necessary to include two links for documentation reference. Both of them will be located in the footer of [CEL Playground](https://playcel.undistro.io/). Please feel free to create the pull request (PR).

Below, you can see an example of how it should be displayed:

Bellow, follow the print as should be:
![image](https://github.com/undistro/cel-playground/assets/38733166/31d587af-86bf-4ae2-a309-0d883435b015)   

Please note that the text "Language definition" should contain an "href" attribute with this link: https://github.com/google/cel-spec/blob/master/doc/langdef.md. For "cel-go", it should be linked to this URL: https://github.com/google/cel-go.

**Comment by lucasjct** [comment]
Thank you for your time, @marcelloale.

We have some considerations about your PR.

We need the links and text, "Language definition" and "cel-go v0.16.0," to be separated. You can use a pipe for this. Please see the example below:

![image](https://github.com/undistro/cel-playground/assets/38733166/1f5016ca-070e-4ff4-92e1-287eea354f56)  

Let me know if you have any question.
Thanks!

**Comment by lucasjct** [comment]
@marcelloale, thank you for your collaboration!

Your PR has been accepted and was merged.
