### ISSUE TITLE
Add Istio example

### ISSUE THREAD

**Issue by matheusfm** [undistro/cel-playground#29]
## Feature Description
Istio also uses CEL for custom metrics. I would like to suggest adding an example for Istio here.

Istio documentation: https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/#use-expressions-for-values

## Is your feature request related to a problem?
No

## What alternatives have you considered?
The examples are in the file: https://github.com/undistro/cel-playground/blob/main/examples.yaml

## Additional Context
If you'd like to work on this or have questions, please comment below for more information.

**Comment by marcelloale** [comment]
Olá @matheusfm como poderia ajudar?

**Comment by matheusfm** [comment]
Hi @marcelloale 
As described above, the proposed idea is to include an Istio example in CEL Playground, as Istio uses CEL for custom metrics.

You can find the file containing all the examples at https://github.com/undistro/cel-playground/blob/main/examples.yaml, and any new examples should be added there.

Each example consists of a CEL expression and input data. 
To create a suitable example, you may need to explore Istio and Envoy.

**Comment by matheusfm** [comment]
It's a good approach to use the example
```
response.code >= 400 || xds.cluster_name == 'BlackHoleCluster' ||  xds.cluster_name == 'PassthroughCluster'
```
for Istio access log filtering.

Just remember to include the associated input data from the CEL Playground example to provide a more complete reference.
