### ISSUE TITLE
Integrated with CEL cost system as in Kubernetes

### ISSUE THREAD

**Issue by cici37** [undistro/cel-playground#34]
## Feature Description
For resource constraint purpose, the existing CEL related features in Kubernetes has been integrated with CEL cost system with cost budget specified. Ref: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#resource-use-by-validation-functions

It would be great if cel-playground could offer the similar power so that user would have a idea on the cost of the cel expression they are going to run.

## Is your feature request related to a problem?
n/a

**Comment by matheusfm** [comment]
Hi @cici37 
Thank you for the suggestion!
Your idea makes a lot of sense, and we appreciate your contribution.
We'll definitely consider implementing it. Any PR is welcome here!

**Comment by knrc** [comment]
FYI PR #43 adds the expression cost to the UI.
